
export enum NativeEvent {
    ASRResult = 'ASRResult',
    ASRConnected = 'ASRConnected',
    ASRClosed = 'ASRClosed',
    TTSConnected = 'TTSConnected',
    TTSClosed = 'TTSClosed',
    TTSEnd = 'TTSEnd',
    TTSStart = 'TTSStart',
    FSRResult = 'FSRResult',
    Device = 'DEVICE',
    DEVICEInfo = 'DEVICEInfo',
    QRCODE = 'QRCODE',
    QRCODEResult = 'QRCODEResult',
    CAMERA = 'CAMERA',
    CAMERARECORDER = 'CAMERARECORDER',
    CAMERAOVERLAY = 'CAMERAOVERLAY',
    CAMERAOVERLAYHIDE = 'CAMERAOVERLAYHIDE',
    CAMERARECORDERRESULT = 'CAMERARECORDERRESULT',
    POSTVIDEODATAFINISHED = 'POSTVIDEODATAFINISHED',
    POSTVIDEODATAERROR = 'POSTVIDEODATAERROR',
    POSTVIDEO = 'POSTVIDEO',
    WXPAY = 'PAYMENT:WXPAY',
    PAYMENTResult = 'PAYMENTResult',
    LOGIN = 'LOGIN',
    APP = 'APP',
    VERSION = 'VERSION',
    VERSIONInfo = 'VERSIONInfo',
}